name: HACS validation
on:
    push:
        branches:
            - main
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
          - name: HACS Action
            uses: "hacs/action@main"
            with:
              category: "plugin"
