name: Release
on:
    push:
        tags:
            - "v*.*.*"
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
            - name: Zip Release
              uses: TheDoctor0/zip-release@0.6.2
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')

              with:
                draft: true
                type: zip
                generate_release_notes: true
                path: dist/*.js
                filename: release.zip
